title: "Carnet de randonnées de Ben"
description: "Mes randos et via ferrata : distances, D+, difficultés, photos et traces GPX."
theme: minima
header_pages: []  


url: "https://benjaminahs.github.io"   # domaine
baseurl: "/rando-de-ben"               # sous-dossier du site de projet

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Affiche les tags
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: rando
      permalink: /randos/:title/
